---
- name: create admin group
  group:
    name: "{{ admin_group }}"

# - name: add admin group to sudoers
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: "%{{ admin_group }}"
#     line: "%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL"

- name: add sudoers to admin group
  user:
    name: "{{ item }}"
    groups: "{{ admin_group }}"
    append: yes
  with_items: "{{ sudoers }}"

- name: get sudoers
  shell: 'getent group {{ admin_group }} | cut -d: -f4 | tr "," "\n"'
  register: present_sudoers
  changed_when: false

- name: removed sudoer drop to users group
  user:
    name: "{{ item }}"
    groups: "{{ user_group }}"
  when: "item != 'ec2-user'"
  with_items: "{{ present_sudoers.stdout_lines | difference(sudoers) }}"
  ignore_errors: yes # ユーザが削除済みの場合があるため
